service: booster-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true